### PR TITLE
Github actions for CI for app script projects

### PR DESCRIPTION
**Pull request by namaggarwal**

### CODE REVIEW

**Comment by namaggarwal** [comment]
For #124

**Comment by contributorpw** [comment]
Cool!

Does it work with the `force` flag?

**Comment by namaggarwal** [comment]
Yes, this action just adds token. So it should work with all the options in clasp command. I use it to automatically push my code and deploy builds :)

**Comment by contributorpw** [comment]
it's so beautiful day. I'm gonna implement this to my public libs. Thank you!

**Comment by namaggarwal** [comment]
There was an issue with the markdown I created. Can you please approve this PR https://github.com/contributorpw/google-apps-script-awesome-list/pull/126

**Pull request merged**
